# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'max906_v2.1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(806, 644)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.status_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.status_label.setObjectName("status_label")
        self.gridLayout_3.addWidget(self.status_label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ip_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip_label.sizePolicy().hasHeightForWidth())
        self.ip_label.setSizePolicy(sizePolicy)
        self.ip_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ip_label.setObjectName("ip_label")
        self.horizontalLayout.addWidget(self.ip_label)
        self.ip_lineEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip_lineEdit.sizePolicy().hasHeightForWidth())
        self.ip_lineEdit.setSizePolicy(sizePolicy)
        self.ip_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.horizontalLayout.addWidget(self.ip_lineEdit)
        self.port_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_label.sizePolicy().hasHeightForWidth())
        self.port_label.setSizePolicy(sizePolicy)
        self.port_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.port_label.setObjectName("port_label")
        self.horizontalLayout.addWidget(self.port_label)
        self.port_lineEdit = QtWidgets.QLineEdit(Form)
        self.port_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.horizontalLayout.addWidget(self.port_lineEdit)
        self.connect_pushButton = QtWidgets.QPushButton(Form)
        self.connect_pushButton.setObjectName("connect_pushButton")
        self.horizontalLayout.addWidget(self.connect_pushButton)
        self.close_pushButton = QtWidgets.QPushButton(Form)
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout.addWidget(self.close_pushButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.output_tab = QtWidgets.QWidget()
        self.output_tab.setObjectName("output_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.output_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.output_textEdit = QtWidgets.QTextEdit(self.output_tab)
        self.output_textEdit.setReadOnly(True)
        self.output_textEdit.setObjectName("output_textEdit")
        self.gridLayout_2.addWidget(self.output_textEdit, 0, 0, 2, 2)
        self.send_pushButton = QtWidgets.QPushButton(self.output_tab)
        self.send_pushButton.setCheckable(False)
        self.send_pushButton.setDefault(False)
        self.send_pushButton.setObjectName("send_pushButton")
        self.gridLayout_2.addWidget(self.send_pushButton, 3, 1, 1, 1)
        self.cmd_lineEdit = QtWidgets.QLineEdit(self.output_tab)
        self.cmd_lineEdit.setObjectName("cmd_lineEdit")
        self.gridLayout_2.addWidget(self.cmd_lineEdit, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.clear_pushButton = QtWidgets.QPushButton(self.output_tab)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.verticalLayout.addWidget(self.clear_pushButton)
        self.save_pushButton = QtWidgets.QPushButton(self.output_tab)
        self.save_pushButton.setObjectName("save_pushButton")
        self.verticalLayout.addWidget(self.save_pushButton)
        self.auto_ip_pushButton = QtWidgets.QPushButton(self.output_tab)
        self.auto_ip_pushButton.setObjectName("auto_ip_pushButton")
        self.verticalLayout.addWidget(self.auto_ip_pushButton)
        self.groupBox = QtWidgets.QGroupBox(self.output_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox.setObjectName("groupBox")
        self.threading_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.threading_spinBox.setGeometry(QtCore.QRect(10, 20, 61, 22))
        self.threading_spinBox.setProperty("value", 4)
        self.threading_spinBox.setObjectName("threading_spinBox")
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.output_tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sms_checkBox = QtWidgets.QCheckBox(self.output_tab)
        self.sms_checkBox.setObjectName("sms_checkBox")
        self.gridLayout.addWidget(self.sms_checkBox, 3, 0, 1, 3)
        self.warm_dis_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.output_tab)
        self.warm_dis_doubleSpinBox.setDecimals(1)
        self.warm_dis_doubleSpinBox.setMaximum(100.0)
        self.warm_dis_doubleSpinBox.setProperty("value", 2.0)
        self.warm_dis_doubleSpinBox.setObjectName("warm_dis_doubleSpinBox")
        self.gridLayout.addWidget(self.warm_dis_doubleSpinBox, 8, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.output_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 8, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.output_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.output_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.warm_pre_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.output_tab)
        self.warm_pre_doubleSpinBox.setDecimals(1)
        self.warm_pre_doubleSpinBox.setMinimum(-20.0)
        self.warm_pre_doubleSpinBox.setMaximum(200.0)
        self.warm_pre_doubleSpinBox.setProperty("value", 40.0)
        self.warm_pre_doubleSpinBox.setObjectName("warm_pre_doubleSpinBox")
        self.gridLayout.addWidget(self.warm_pre_doubleSpinBox, 7, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.output_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.warm_status_label = QtWidgets.QLabel(self.output_tab)
        self.warm_status_label.setText("")
        self.warm_status_label.setObjectName("warm_status_label")
        self.gridLayout.addWidget(self.warm_status_label, 6, 2, 1, 1)
        self.warn_checkBox = QtWidgets.QCheckBox(self.output_tab)
        self.warn_checkBox.setChecked(True)
        self.warn_checkBox.setObjectName("warn_checkBox")
        self.gridLayout.addWidget(self.warn_checkBox, 0, 0, 1, 1)
        self.warm_checkBox = QtWidgets.QCheckBox(self.output_tab)
        self.warm_checkBox.setObjectName("warm_checkBox")
        self.gridLayout.addWidget(self.warm_checkBox, 6, 0, 1, 1)
        self.warn_status_label = QtWidgets.QLabel(self.output_tab)
        self.warn_status_label.setText("")
        self.warn_status_label.setObjectName("warn_status_label")
        self.gridLayout.addWidget(self.warn_status_label, 0, 2, 1, 1)
        self.email_checkBox = QtWidgets.QCheckBox(self.output_tab)
        self.email_checkBox.setObjectName("email_checkBox")
        self.gridLayout.addWidget(self.email_checkBox, 4, 0, 1, 3)
        self.warn_pre_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.output_tab)
        self.warn_pre_doubleSpinBox.setDecimals(1)
        self.warn_pre_doubleSpinBox.setMinimum(-20.0)
        self.warn_pre_doubleSpinBox.setMaximum(200.0)
        self.warn_pre_doubleSpinBox.setSingleStep(1.0)
        self.warn_pre_doubleSpinBox.setProperty("value", 50.0)
        self.warn_pre_doubleSpinBox.setObjectName("warn_pre_doubleSpinBox")
        self.gridLayout.addWidget(self.warn_pre_doubleSpinBox, 1, 2, 1, 1)
        self.warn_dis_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.output_tab)
        self.warn_dis_doubleSpinBox.setDecimals(1)
        self.warn_dis_doubleSpinBox.setMinimum(-20.0)
        self.warn_dis_doubleSpinBox.setMaximum(200.0)
        self.warn_dis_doubleSpinBox.setProperty("value", 1.0)
        self.warn_dis_doubleSpinBox.setObjectName("warn_dis_doubleSpinBox")
        self.gridLayout.addWidget(self.warn_dis_doubleSpinBox, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 2, 1, 1)
        self.tabWidget.addTab(self.output_tab, "")
        self.data_tab = QtWidgets.QWidget()
        self.data_tab.setObjectName("data_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.data_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.matplotlibwidget_dynamic = MatDynamicWidget(self.data_tab)
        self.matplotlibwidget_dynamic.setEnabled(False)
        self.matplotlibwidget_dynamic.setObjectName("matplotlibwidget_dynamic")
        self.gridLayout_4.addWidget(self.matplotlibwidget_dynamic, 1, 0, 1, 2)
        self.plot_dynamic_pushButton = QtWidgets.QPushButton(self.data_tab)
        self.plot_dynamic_pushButton.setObjectName("plot_dynamic_pushButton")
        self.gridLayout_4.addWidget(self.plot_dynamic_pushButton, 0, 1, 1, 1)
        self.plot_stop_pushButton = QtWidgets.QPushButton(self.data_tab)
        self.plot_stop_pushButton.setObjectName("plot_stop_pushButton")
        self.gridLayout_4.addWidget(self.plot_stop_pushButton, 0, 0, 1, 1)
        self.tabWidget.addTab(self.data_tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 2, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.cmd_lineEdit.returnPressed.connect(self.send_pushButton.click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MLX90614-V2"))
        self.status_label.setText(_translate("Form", "未连接"))
        self.ip_label.setText(_translate("Form", "ip地址"))
        self.port_label.setText(_translate("Form", "端口"))
        self.connect_pushButton.setText(_translate("Form", "连接"))
        self.close_pushButton.setText(_translate("Form", "断开"))
        self.send_pushButton.setText(_translate("Form", "ok"))
        self.clear_pushButton.setText(_translate("Form", "清空输出"))
        self.save_pushButton.setText(_translate("Form", "保存日志"))
        self.auto_ip_pushButton.setText(_translate("Form", "自动获取ip"))
        self.groupBox.setTitle(_translate("Form", "扫描线程"))
        self.label.setText(_translate("Form", "命令行"))
        self.sms_checkBox.setText(_translate("Form", "短信通知"))
        self.label_4.setText(_translate("Form", "温    差"))
        self.label_5.setText(_translate("Form", "预设温度"))
        self.label_3.setText(_translate("Form", "温    差"))
        self.label_2.setText(_translate("Form", "预设温度"))
        self.warn_checkBox.setText(_translate("Form", "温度报警"))
        self.warm_checkBox.setText(_translate("Form", "恒温系统"))
        self.email_checkBox.setText(_translate("Form", "邮件通知"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.output_tab), _translate("Form", "监控输出"))
        self.plot_dynamic_pushButton.setText(_translate("Form", "动态分析"))
        self.plot_stop_pushButton.setText(_translate("Form", "停止分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.data_tab), _translate("Form", "数据报表"))
from MatplotWidget import MatDynamicWidget
